apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-service
  namespace: efk
  labels:
    app: simple-webapp
    job: flask-api
spec:
  selector:
    app: simple-webapp
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 5001
    nodePort: 30001 

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /metrics
  selector:
    matchLabels:
      app: simple-webapp
