name: chedi workflow

on:
  push:  

jobs:
  Build_Push_to_DockerHub:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: python-webapp/
    #     push: true
    #     tags: chedi1/app:v1

    
    - name: Generate Kubeconfig and Certs
      run: |
        echo ${{ secrets.KUBECONFIG }} > ./kubeconfig
        echo ${{ secrets.CLIENT_K8S_CERT }} > ./client.crt
        echo ${{ secrets.CLIENT_K8S_KEY }} > ./client.key

    - name: Deploy to Kubernetes
      run: |
        kubectl --kubeconfig=./kubeconfig get pods


    - name: Clean-Up
      run: |
        rm ./kubeconfig
        rm ./client.cert    

    # - name: Generate Kubeconfig and Certs
    #   run: |
    #     kubectl get pods
    