name: chedi workflow

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Switch to application directory
      run: ls -ll

    - name: Switch to application directory
      run: cd python-webapp/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     tags: chedi1/app:v1
        
    # - name: Generate Kubeconfig and Certs
    #   run: |
    #     echo ${{ secrets.KUBECONFIG }} > ./deploy.kubeconfig
    #     echo ${{ secrets.CERTS }} > ./cert

    # - name: Kubernetes Deployment
    #   uses: TanmoySG/k-deploy-action@v0.2.2-alpha
    #   with:
    #     kubeconfig: ./deploy.kubeconfig
    #     namespace: 'default'
    #     manifest: k8-deployment/python-app-deployment.yaml

    # - name: Clean-Up
    #   run: |
    #     rm path/to/deploy.kubeconfig
    #     rm path/to/cert    